### ISSUE TITLE
[Bug report] create MySQL table using func in default value can be done, but cannot load it

### ISSUE THREAD

**Issue by zhoukangcn** [apache/gravitino#2946]
### Version

main branch

### Describe what's wrong

create a MySQL table using funciton in default value, this request get an excepiton 

```
Failed to operate object [test_table5] operation [CREATE] under [test], reason [Text 'current_timestamp()' could not be parsed at index 0]
````

But in fact, it has already been created in MySQL

### Error message and/or stacktrace

```
2024-04-15 18:05:44.279 WARN [Gravitino-webserver-59] [com.datastrato.gravitino.server.web.rest.ExceptionHandlers$TableExceptionHandler.handle(ExceptionHandlers.java:126)] - Failed to operate table(s) [exmaple_table] operation [LOAD] under schema [test], reason [Text 'current_timestamp()' could not be parsed at index 0]
java.time.format.DateTimeParseException: Text 'current_timestamp()' could not be parsed at index 0
  at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[?:1.8.0_312]
  at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[?:1.8.0_312]
  at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[?:1.8.0_312]
  at com.datastrato.gravitino.catalog.mysql.converter.MysqlColumnDefaultValueConverter.toGravitino(MysqlColumnDefaultValueConverter.java:88) ~[?:?]
  at com.datastrato.gravitino.catalog.jdbc.operation.JdbcTableOperations.getBasicJdbcColumnInfo(JdbcTableOperations.java:426) ~[?:?]
  at com.datastrato.gravitino.catalog.jdbc.operation.JdbcTableOperations.load(JdbcTableOperations.java:161) ~[?:?]
  at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.loadTable(JdbcCatalogOperations.java:277) ~[?:?]
  at com.datastrato.gravitino.catalog.TableOperationDispatcher.lambda$loadTable$2(TableOperationDispatcher.java:83) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:108) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:72) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithTableOps(CatalogManager.java:103) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.catalog.TableOperationDispatcher.lambda$loadTable$3(TableOperationDispatcher.java:83) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:69) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.catalog.TableOperationDispatcher.loadTable(TableOperationDispatcher.java:81) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.catalog.TableEventDispatcher.loadTable(TableEventDispatcher.java:58) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.server.web.rest.TableOperations.lambda$loadTable$4(TableOperations.java:141) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.server.web.rest.TableOperations.lambda$loadTable$5(TableOperations.java:140) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
  at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
  at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_312]
  at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
  at com.datastrato.gravitino.server.web.rest.TableOperations.loadTable(TableOperations.java:135) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
```

### How to reproduce

```
curl -X POST -H "Accept: application/vnd.gravitino.v1+json" \
-H "Content-Type: application/json" -d '
{
  "name": "test_table5",
  "comment": "This is an example table",
  "columns": [
    {
      "name": "id",
      "type": "integer",
      "comment": "id column comment",
      "nullable": false,
      "autoIncrement": false,
      "defaultValue": {
        "type": "literal",
        "dataType": "integer",
        "value": "-1"
      }
    },
    {
      "name": "StartingDate",
      "type": "timestamp",
      "comment": "StartingDate column comment",
      "nullable": false,
      "autoIncrement": false,
      "defaultValue": {
        "type": "function",
        "funcName": "current_timestamp",
        "funcArgs": []
      }
    }
  ]
}' http://localhost:8090/api/metalakes/metalake/catalogs/mysql_catalog/schemas/test/tables
```

**Comment by mchades** [comment]
I think this issue was resolved by #4301, could you please help to validate? @zhoukangcn

**Comment by mchades** [comment]
I'm going to close this issue as I've verified locally that this issue is fixed, feel free to reopen if there are still issues

**Comment by zhoukangcn** [comment]
@mchades I had test it with main branch, I found this bug still exists. So I will reopen this issue.

**Comment by mchades** [comment]
> @mchades I had test it with main branch, I found this bug still exists. So I will reopen this issue.

I used the table creation request described by you and was able to create it successfully. Can you provide more detailed errors and reproduction steps for failures?

**Comment by zhoukangcn** [comment]
> > @mchades I had test it with main branch, I found this bug still exists. So I will reopen this issue.
> 
> I used the table creation request described by you and was able to create it successfully. Can you provide more detailed errors and reproduction steps for failures?

Sorry, I use mariadb as mysql catalog. So there is a little different in default value for type datetime. 

MySQL is 
```
CREATE TABLE `test_table10` (
  `id` int NOT NULL DEFAULT '-1' COMMENT 'id column comment',
  `StartingDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'StartingDate column comment'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='This is an example table (From Gravitino, DO NOT EDIT: gravitino.v1.uid2578171798626417481)'
```
mariadb is
```
CREATE TABLE `test_table10` (
  `id` int(11) NOT NULL DEFAULT -1 COMMENT 'id column comment',
  `StartingDate` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'StartingDate column comment'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This is an example table (From Gravitino, DO NOT EDIT: gravitino.v1.uid1019119279519593239)'
```

**Comment by mchades** [comment]
> > > @mchades I had test it with main branch, I found this bug still exists. So I will reopen this issue.
> > 
> > 
> > I used the table creation request described by you and was able to create it successfully. Can you provide more detailed errors and reproduction steps for failures?
> 
> Sorry, I use mariadb as mysql catalog. So there is a little different in default value for type datetime.
> 
> MySQL is
> 
> ```
> CREATE TABLE `test_table10` (
>   `id` int NOT NULL DEFAULT '-1' COMMENT 'id column comment',
>   `StartingDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'StartingDate column comment'
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='This is an example table (From Gravitino, DO NOT EDIT: gravitino.v1.uid2578171798626417481)'
> ```
> 
> mariadb is
> 
> ```
> CREATE TABLE `test_table10` (
>   `id` int(11) NOT NULL DEFAULT -1 COMMENT 'id column comment',
>   `StartingDate` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'StartingDate column comment'
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This is an example table (From Gravitino, DO NOT EDIT: gravitino.v1.uid1019119279519593239)'
> ```

Could you please provide the error stack as well?

**Comment by zhoukangcn** [comment]
```
2024-08-06 10:01:37.474 ERROR [Gravitino-webserver-48] [org.apache.gravitino.server.web.rest.ExceptionHandlers$BaseExceptionHandler.handle(ExceptionHandlers.java:583)] - Failed to operate object [test_table10] operation [LOAD] under [test], reason [Text 'current_timestamp()' could not be parsed at index 0]
java.time.format.DateTimeParseException: Text 'current_timestamp()' could not be parsed at index 0
  at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[?:1.8.0_312]
  at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[?:1.8.0_312]
  at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[?:1.8.0_312]
  at org.apache.gravitino.catalog.mysql.converter.MysqlColumnDefaultValueConverter.toGravitino(MysqlColumnDefaultValueConverter.java:96) ~[?:?]
  at org.apache.gravitino.catalog.jdbc.operation.JdbcTableOperations.getBasicJdbcColumnInfo(JdbcTableOperations.java:489) ~[?:?]
  at org.apache.gravitino.catalog.jdbc.operation.JdbcTableOperations.load(JdbcTableOperations.java:191) ~[?:?]
  at org.apache.gravitino.catalog.jdbc.JdbcCatalogOperations.loadTable(JdbcCatalogOperations.java:312) ~[?:?]
  at org.apache.gravitino.catalog.TableOperationDispatcher.lambda$internalLoadTable$23(TableOperationDispatcher.java:445) ~[gravitino-core-0.6.0-SNAPSHOT.jar:?]
  at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:130) ~[gravitino-core-0.6.0-SNAPSHOT.jar:?]
  at org.apache.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:86) ~[gravitino-core-0.6.0-SNAPSHOT.jar:?]
```

**Comment by mchades** [comment]
Have you updated your local code to the latest version? I still cannot reproduce the issue in MySQL, and I found that the existing integration tests already include your case:
https://github.com/apache/gravitino/blob/97839ee6b19fd11484ae4a1de7942e7c3918b876/catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java#L497

So, I suspect it's a MariaDB issue. Can you verify it using MySQL?

**Comment by zhoukangcn** [comment]
> Have you updated your local code to the latest version? I still cannot reproduce the issue in MySQL, and I found that the existing integration tests already include your case:
> 
> https://github.com/apache/gravitino/blob/97839ee6b19fd11484ae4a1de7942e7c3918b876/catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java#L497
> 
> So, I suspect it's a MariaDB issue. Can you verify it using MySQL?

Yes, It's a MariaDB issue, MySQL is works well.

My mistake, I didn't notice that I was using MariaDB when reporting the bug.
